### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './jsons/converted_train2019.json'

### ISSUE THREAD

**Issue by Angelina1996** [AlessandroSaviolo/iNaturalist-2019#1]
Hi, source code does not contain the jsons/converted_train2019.json file, could you please provide the required file

**Comment by AlessandroSaviolo** [comment]
Hi Angelina. Have a look at the data provided by the challenge: https://www.kaggle.com/c/inaturalist-2019-fgvc6/data
